# Generated by Django 4.1.7 on 2023-02-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('name', models.TextField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('skills_used', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('url_live', models.CharField(max_length=200)),
                ('source_code', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('skill_1', models.CharField(max_length=100)),
                ('skill_1_1', models.CharField(max_length=100)),
                ('skill_1_2', models.CharField(max_length=100)),
                ('skill_1_3', models.CharField(max_length=100)),
                ('skill_1_4', models.CharField(max_length=100)),
                ('skill_1_5', models.CharField(max_length=100)),
                ('skill_1_6', models.CharField(max_length=100)),
                ('skill_1_7', models.CharField(max_length=100)),
                ('skill_1_8', models.CharField(max_length=100)),
                ('skill_1_9', models.CharField(max_length=100)),
                ('skill_1_10', models.CharField(max_length=100)),
                ('skill_1_11', models.CharField(max_length=100)),
                ('skill_1_12', models.CharField(max_length=100)),
            ],
        ),
    ]
