# Generated by Django 4.1.7 on 2023-03-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.RemoveField(
            model_name='about',
            name='email',
        ),
        migrations.RemoveField(
            model_name='about',
            name='name',
        ),
        migrations.RemoveField(
            model_name='about',
            name='phone',
        ),
        migrations.AddField(
            model_name='about',
            name='photo_background',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='about',
            name='resume',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='about',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
