# Generated by Django 4.1.7 on 2023-03-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_delete_resume_remove_about_email_remove_about_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='resume_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
