# Generated by Django 4.1.7 on 2023-03-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_about_resume_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='photo_background',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
