# Generated by Django 4.1.7 on 2023-03-21 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_about_photo_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='photo_background',
        ),
    ]
